site_name: 笑笑的书
site_url: https://smilingwayne.github.io/Readingxiaoxiao/

nav:
  - Home: index.md
  - 诗:
      - 外国诗: foreignPoetry.md
      - 中国诗: chinesePoetry.md
  - 哲学: philosophy.md
  - 浪漫主义: romanticism.md
  - 碎碎念: pieces.md
  - 考研:
      - 我的规划: yan/yanPlans.md
      - 我的用书: yan/yanBooks.md
      - 闲聊: yan/yanTalks.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"

      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  # palette:
  #   accent: deep orange

plugins:
  - search
