site_name: 笑笑的书
site_url: https://smilingwayne.github.io/Readingxiaoxiao/

nav:
  - Home: index.md
  - 诗:
      - Poems/index.md
      - 外国诗:
          # - Poems/index.md
          - 愤怒与神秘: Poems/Anger_and_mystery.md
          - 恶之花: Poems/Fleurs_du_mal.md
          - 是你在歌唱？是我在遐想: Poems/Yesenin.md
          - 穿裤子的云: Poems/Mayakovsky.md
          - 卢济塔尼亚人之歌: Poems/Luzitania.md
          - 生命与希望之歌: Poems/Poems_de_life_hope.md
          - 伊利亚特: Poems/Illiad.md
          - 德国，一个冬天的童话: Poems/German_winter_fairytale.md
          - 坎特伯雷故事集: Poems/Canterbery.md
          - 我用古典的方式爱过你: Poems/Emily.md
          - 散落碎片: Poems/Middle_east.md
      - 中国诗:
          - 辛弃疾词: Poems/Xinqiji_ci.md
          - 木心诗选: Poems/Muxin.md

  - 戏剧:
      - 浮士德: Plays/Faust.md
      - 广岛之恋: Plays/Hiroshima.md
      - 爱的徒劳: Plays/Loves_labors_lost.md
      - 奥赛罗: Plays/Othello.md
      - 麦克白: Plays/Macbeth.md
      - 哈姆雷特: Plays/Hamlet.md
      - 亨利四世: Plays/HenryIV.md
      - 暴风雨: Plays/Storms.md
      - 海鸥: Plays/Seagull.md
      - 美狄亚: Plays/Media.md
      - 牡丹亭: Plays/Mu_dan_ting.md
      - 桃花扇: Plays/Tao_hua_shan.md

  - 艺术:
      - 拉斐尔前派的梦: Arts/Pre_Raphael.md
      - 黑夜的蝴蝶: Arts/Butterfly_at_night.md
      - 左岸,从人民阵线到冷战作家: Arts/Left_bank.md
      - 非主流艺术史: Arts/Art_history_unfashioned.md
      - 艺术引导人生——德拉克洛瓦私人日记: Arts/Delacroix.md
      - 法国制造——法国文化关键词: Arts/Made_in_French.md
      - 达达和超现实主义: Arts/Dada_surrealism.md
      - 贝多芬的骰子: Arts/Beethoven.md
      - 爱的艺术: Arts/Arts_of_love.md
      - 艺术的故事: Arts/Stories_of_art.md

  - 哲学:
      - 相似之书: Philosophy/Book_of_resemblance.md
      - 政治学与女性主义: Philosophy/Politics_feminism.md
      - 民族国家间的和平与战争: Philosophy/Peace_war_in_nation_state.md
      - 福柯(牛津通识读本): Philosophy/Facult.md
      - 浪漫主义(牛津通识读本): Philosophy/Romanticism.md
      - 论政府: Philosophy/Government.md
      - 哲思与海——一部诗意的哲学随笔: Philosophy/Phi_and_sea.md
      - 记忆之场: Philosophy/Field_of_memory.md
      - 倦怠社会: Philosophy/Society_of_fatigue.md
      - 法国知识分子的世纪: Philosophy/Century_of_intellects_in_France.md
      - 东风——法国知识分子与60年代的遗产: Philosophy/Eastern_wind.md
      - 利奥波德国王的鬼魂: Philosophy/King_leopolds_ghost.md
      - 禅与摩托车维修艺术: Philosophy/Zen_motor_maintanence.md
      - 法国资产阶级史(上): Philosophy/Bourgeoisie.md
      - 西太平洋上的航海者: Philosophy/Voyagers_western_pacific_ocean.md

  - 文学:
      - 西方正典: Literature/Western_classic.md

  - 碎碎念: pieces.md
  - 考研:
      - 我的规划: yan/yanPlans.md
      - 我的用书: yan/yanBooks.md
      - 闲聊: yan/yanTalks.md
  - 想/在做的事:
      - 书: ToDo/ToRead.md
      - 术: ToDo/ToCode.md

theme:
  name: material
  features:
    - navigation.tabs
    # - navigation.sections
    - navigation.expand
    # - navigation.top
    - navigation.indexes
  palette:
    - media: "(prefers-color-scheme: light)"

      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  # palette:
  #   accent: deep orange

plugins:
  - search
extra:
  social:
    - icon: fontawesome/brands/zhihu
      link: https://www.zhihu.com/people/wang-zhi-xiao-49-5
    - icon: fontawesome/brands/github
      link: https://github.com/SmilingWayne

copyright: Copyright &copy; 2001 - 2022 xiaoxiaoWayne
